### ISSUE TITLE
Find "hero" picture for main page

### ISSUE THREAD

**Issue by jbelien** [flosskosova/foss4g-2023#12]
Find a picture to replace the "blue screen".
Picture should be dark enough so the text is readable.

**Comment by jbelien** [comment]
Also suggested by @sidorelauku : change blue color by something else

**Comment by sidorelauku** [comment]
I think that the logo uses another blue color, which is a bit darker. But we should ask the designer for the color palette.

**Comment by jbelien** [comment]
Request from Valmir: use video from SotM SEE!
