### ISSUE TITLE
Find header picture for "Register" page

### ISSUE THREAD

**Issue by jbelien** [flosskosova/foss4g-2023#13]
Find header picture for "Register" page: https://2023.foss4g.org/register/
Picture should be dark enough so the text is readable.

**Comment by jbelien** [comment]
I've put a "random" picture for now but we need to find a picture related to the venue/topic.

**Comment by valmirmustafa** [comment]
![Image](https://user-images.githubusercontent.com/47977202/197335151-22a84ed0-2f45-40c8-999d-1096c8879c13.jpg)
