### ISSUE TITLE
Find header picture for "Call for papers" page

### ISSUE THREAD

**Issue by jbelien** [flosskosova/foss4g-2023#14]
Find header picture for "Call for papers" page: https://2023.foss4g.org/call-for-papers/
Picture should be dark enough so the text is readable.

**Comment by jbelien** [comment]
I've put a "random" picture for now but we need to find a picture related to the venue/topic.

**Comment by valmirmustafa** [comment]
![Image](https://user-images.githubusercontent.com/47977202/197335161-beee19a4-6412-4bb5-93fd-b4fd8ba3639e.jpg)
