### ISSUE TITLE
Find header picture for "Schedule" page

### ISSUE THREAD

**Issue by jbelien** [flosskosova/foss4g-2023#15]
Find header picture for "Schedule" page: https://2023.foss4g.org/schedule/
 Picture should be dark enough so the text is readable.

**Comment by jbelien** [comment]
I've put a "random" picture for now but we need to find a picture related to the venue/topic.

**Comment by valmirmustafa** [comment]
![Image](https://user-images.githubusercontent.com/47977202/197335199-049b9fa7-dc49-4733-b71a-ff0abeb2af49.jpg)

**Comment by raymondnijssen** [comment]
![Image](https://user-images.githubusercontent.com/681851/197338602-00db096b-bb1f-4caf-accf-4f8d9e7b799f.JPG)

**Comment by jbelien** [comment]
I also needed a picture for the new "About" page, so I'll use @valmirmustafa's picture for the "About" page and @raymondnijssen's picture for the "Schedule" page. 👍 

Thank you both!
