### ISSUE TITLE
Make logo bigger and font on menu bold and a bit bigger on size.

### ISSUE THREAD

**Issue by sidorelauku** [flosskosova/foss4g-2023#24]
Currently the logos are very small, both main menu and footer. We should try to make those a bit bigger so the wording Prizren 2023 is readable.  

Also the font on menu is very light and small, which makes it not very readable. 

@jbelien let me know if you would like me to do this, or you want to change it yourself.

**Comment by jbelien** [comment]
> @jbelien let me know if you would like me to do this, or you want to change it yourself.

You're more than welcome to do it yourself! 👍 
If we start working together, I suggest we go through Pull Requests to add new feature or change things (if it works for you, of course).

**Comment by sidorelauku** [comment]
ok this works for me as well :)
