### ISSUE TITLE
Footer background color, try the colors of the logo to see what looks better.

### ISSUE THREAD

**Issue by jbelien** [flosskosova/foss4g-2023#46]
Colors available here: https://drive.google.com/drive/mobile/folders/1gTzvScls8zBtjUlb3AN6WfjTu_KPwPXq/152fMGqHxEHlM4iKbBpe7zjOtfpXqSRQs/1wCgvf0Xgyz76wa08alVdpbG7f7VPLmyB

**Comment by sidorelauku** [comment]
The titles for each header on the footer as are headings, on MR #31 will be converted in bold style.
