### ISSUE TITLE
PHONE version  - remove blue banner above video (header)

### ISSUE THREAD

**Issue by jbelien** [flosskosova/foss4g-2023#48]

**Comment by jbelien** [comment]
Reference: 

![Image](https://user-images.githubusercontent.com/1150563/195779291-3c4e0da4-25c3-4285-8734-ea737b38516d.png)

**Comment by sidorelauku** [comment]
This is caused by the css of the video, `position: absolute`, and only appears on the main page. I think would be resolved by changing it to `position: fixed`.
