### ISSUE TITLE
put an red colour overlay on top of the video / photo?

### ISSUE THREAD

**Issue by jbelien** [flosskosova/foss4g-2023#50]
Here is an example how it should look like. 
Transparency/overlay 30% of red colour from the logo | RED - #ed5d5d

[

![Image](https://user-images.githubusercontent.com/47977202/195832892-35f13ba7-52ea-4b6c-9e91-b5eafa04b036.png)

](url)

**Comment by raymondnijssen** [comment]
I'm sorry, I got it working for an image, but I don't manage to get it working for the video... :(

**Comment by jbelien** [comment]
> I'm sorry, I got it working for an image, but I don't manage to get it working for the video... :(

Don't worry. I'll have a look ASAP. 😃

**Comment by raymondnijssen** [comment]
![Image](https://user-images.githubusercontent.com/681851/197344388-2523a4c3-dec4-4a1b-9808-c9ad2a7369bb.png)

**Comment by raymondnijssen** [comment]
For the above effect, I put this in the div where the venue-img div:
```
                          <style>
                            .red-overlay {
                              background-color: #ed5d5d;
                              z-index: -1;
                              opacity: 0.7;
                              height: 100%;
                              width: 100%;
                            }
                          </style>
                          <div class="red-overlay"></div>
```

**Comment by raymondnijssen** [comment]
But I'm really not into css!

**Comment by sidorelauku** [comment]
On the pull request that I created it only adds the overlay on the main page. Should we add it over all the photos on other pages? @jbelien
