### ISSUE TITLE
Change FOSS4G logo to PNG

### ISSUE THREAD

**Issue by jbelien** [flosskosova/foss4g-2023#52]

**Comment by raymondnijssen** [comment]
Where's the logo? What dimensions (px) should the png become?

**Comment by jbelien** [comment]
https://drive.google.com/drive/mobile/folders/1gTzvScls8zBtjUlb3AN6WfjTu_KPwPXq/152fMGqHxEHlM4iKbBpe7zjOtfpXqSRQs/1LC2_16a-lxKOBACWaTZ7AUHK74UAbzl4
