### ISSUE TITLE
Add this table to registration page

### ISSUE THREAD

**Issue by jbelien** [flosskosova/foss4g-2023#69]
Albert suggested that we go with svg file, as it doesn't lose quality 

![Image](https://user-images.githubusercontent.com/47977202/199206214-d8f4e114-17a7-4883-a78d-d0aa42ccd694.png)
![Image](https://user-images.githubusercontent.com/47977202/199206215-70129681-77bc-4b18-a7ab-29ca5f1dbab7.svg)

**Comment by jbelien** [comment]
@valmirmustafa Could you send just the table, without the "Registration Fees" title ?

**Comment by valmirmustafa** [comment]
![Image](https://user-images.githubusercontent.com/47977202/200162320-f66f2aea-e103-4092-8f1d-2ef8f7c939b7.svg)
![Image](https://user-images.githubusercontent.com/47977202/200162319-9b8ea8a0-69b8-4fd9-a81c-367ffddcca1b.png)
