### ISSUE TITLE
change this two photos on main page at Venue section

### ISSUE THREAD

**Issue by jbelien** [flosskosova/foss4g-2023#72]
![Image](https://user-images.githubusercontent.com/47977202/199604664-928e88ba-47ff-4280-9b8b-929d9606d1d8.jpg)
![Image](https://user-images.githubusercontent.com/47977202/199604666-c43852a3-9442-4467-83bd-4fb0472ee9f8.jpg)

**Comment by jbelien** [comment]
@valmirmustafa No worries but what picture do I place instead ?

**Comment by valmirmustafa** [comment]
Changed my mind, do not change them. 

Can you just put red color on top of them, as in the other photos?
