### ISSUE TITLE
Update FAQ

### ISSUE THREAD

**Issue by jbelien** [flosskosova/foss4g-2023#74]
> can you fix FAQ once more? 
> Looks at code of conduct, make it similar to that. 
> 
> Titles (alfabeti):
> When and where
> Registration
> 
> Subtitles (alfabeti):
> All the questions?
> 
> Paragraphs (inter):
> All the answers
> 
> *-- Request from @valmirmustafa*

**Comment by sidorelauku** [comment]
this is done.
