### ISSUE TITLE
Put red color on top of venue pictures

### ISSUE THREAD

**Issue by jbelien** [flosskosova/foss4g-2023#76]
> Can you just put red color on top of them, as in the other photos?

_Originally posted by @valmirmustafa in https://github.com/flosskosova/foss4g-2023/issues/72#issuecomment-1304744684_

**Comment by jbelien** [comment]
@sidorelauku If you have a moment, could you also apply your overlay magic on the pictures of the venue ? Thanks. 😃

**Comment by sidorelauku** [comment]
Done with PR #77
