### ISSUE TITLE
remove this table on registration page

### ISSUE THREAD

**Issue by jbelien** [flosskosova/foss4g-2023#78]
![Image](https://user-images.githubusercontent.com/47977202/200580282-55d9e5ef-acd0-4081-bcd5-bd609f789fab.png)

*-- Created by @valmirmustafa*

**Comment by jbelien** [comment]
@valmirmustafa No worries but how will people actually buy tickets then ?

**Comment by valmirmustafa** [comment]
@jbelien a think we will redirect them to pretix so there they can navigate and choose which ticket to buy

**Comment by valmirmustafa** [comment]
Check if embedded pretix ticketing works. If it works please remove it. 

If it doesn't, I would still prefer people to redirect to pretix for buying tickets, is way easier and more informative for ticket purchasing.

**Comment by jbelien** [comment]
Done in acbcf32a1e279dc1b2791819d3995dfff7a2880a
