### ISSUE TITLE
Use blue instead of red colour for check icons?

### ISSUE THREAD

**Issue by raymondnijssen** [flosskosova/foss4g-2023#82]
Red means no/wrong where the icons mean yes/right, which is appearing odd and unclear to me.

![image](https://user-images.githubusercontent.com/681851/202125973-a865d45f-faa9-426e-a996-65652772d7fd.png)

**Comment by jbelien** [comment]
Ping @valmirmustafa

**Comment by valmirmustafa** [comment]
it is ok, lets leave them as they are :)
